version: '2'
services:
  mailer:
    image: docker-node-express-mongoapp
    build: ./Web
    command: bash -c "sleep 40 && npm start"
    ports:
      - "4003:4003"
    volumes:
      - ./Web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"